version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
      - cd backend
      - npm install
      - cd ../client
      - npm install
  build:
    commands:
      - echo Build started on `date`
      # Build the React app
      - cd ../client
      - npm run build
      # Prepare backend for deployment
      - cd ../backend
      - npm run build # if you have a build step for your backend

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: no
