version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Entering dashboardclient directory
      - cd dashboardclient
      - echo Installing frontend dependencies
      - npm install
  build:
    commands:
      - echo Building frontend
      - npm run build
  post_build:
    commands:
      - echo Frontend build complete
      - echo Listing contents of dashboardclient directory
      - ls -la dashboardclient
      - echo Listing contents of build directory
      - ls -la dashboardclient/dist

artifacts:
  files:
    - '**/*'
  base-directory: 'dashboardclient/dist' # Ensure this matches your build output directory
